# Generated by Django 3.2.3 on 2021-06-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtosmodel',
            name='icone',
            field=models.CharField(choices=[('best_box', 'Caixa')], default=1, max_length=13, verbose_name='icone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtosmodel',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Fabricante'),
        ),
    ]
